//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesEscaleras.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Puntuacion", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Puntuacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Jugador1 JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Partida PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short puntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short turnosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Jugador1 Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Partida Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartidaField, value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short puntos {
            get {
                return this.puntosField;
            }
            set {
                if ((this.puntosField.Equals(value) != true)) {
                    this.puntosField = value;
                    this.RaisePropertyChanged("puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short turnos {
            get {
                return this.turnosField;
            }
            set {
                if ((this.turnosField.Equals(value) != true)) {
                    this.turnosField = value;
                    this.RaisePropertyChanged("turnos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Jugador1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Cuenta1 CuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Puntuacion[] PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Cuenta1 Cuenta {
            get {
                return this.CuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaField, value) != true)) {
                    this.CuentaField = value;
                    this.RaisePropertyChanged("Cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Puntuacion[] Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntuacionField, value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apodo {
            get {
                return this.apodoField;
            }
            set {
                if ((object.ReferenceEquals(this.apodoField, value) != true)) {
                    this.apodoField = value;
                    this.RaisePropertyChanged("apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Partida", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Partida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Puntuacion[] PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Tablero TableroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short num_jugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tiempo_finField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime tiempo_inicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Puntuacion[] Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntuacionField, value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Tablero Tablero {
            get {
                return this.TableroField;
            }
            set {
                if ((object.ReferenceEquals(this.TableroField, value) != true)) {
                    this.TableroField = value;
                    this.RaisePropertyChanged("Tablero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short num_jugadores {
            get {
                return this.num_jugadoresField;
            }
            set {
                if ((this.num_jugadoresField.Equals(value) != true)) {
                    this.num_jugadoresField = value;
                    this.RaisePropertyChanged("num_jugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tiempo_fin {
            get {
                return this.tiempo_finField;
            }
            set {
                if ((this.tiempo_finField.Equals(value) != true)) {
                    this.tiempo_finField = value;
                    this.RaisePropertyChanged("tiempo_fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tiempo_inicio {
            get {
                return this.tiempo_inicioField;
            }
            set {
                if ((this.tiempo_inicioField.Equals(value) != true)) {
                    this.tiempo_inicioField = value;
                    this.RaisePropertyChanged("tiempo_inicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Cuenta1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Jugador1 JugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string saltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool validadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Jugador1 Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salt {
            get {
                return this.saltField;
            }
            set {
                if ((object.ReferenceEquals(this.saltField, value) != true)) {
                    this.saltField = value;
                    this.RaisePropertyChanged("salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool validada {
            get {
                return this.validadaField;
            }
            set {
                if ((this.validadaField.Equals(value) != true)) {
                    this.validadaField = value;
                    this.RaisePropertyChanged("validada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tablero", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Tablero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Casilla[] CasillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Ficha[] FichaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.FondoTablero[] FondoTableroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Partida PartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuadriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short no_casillasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Casilla[] Casilla {
            get {
                return this.CasillaField;
            }
            set {
                if ((object.ReferenceEquals(this.CasillaField, value) != true)) {
                    this.CasillaField = value;
                    this.RaisePropertyChanged("Casilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Ficha[] Ficha {
            get {
                return this.FichaField;
            }
            set {
                if ((object.ReferenceEquals(this.FichaField, value) != true)) {
                    this.FichaField = value;
                    this.RaisePropertyChanged("Ficha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.FondoTablero[] FondoTablero {
            get {
                return this.FondoTableroField;
            }
            set {
                if ((object.ReferenceEquals(this.FondoTableroField, value) != true)) {
                    this.FondoTableroField = value;
                    this.RaisePropertyChanged("FondoTablero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Partida Partida {
            get {
                return this.PartidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PartidaField, value) != true)) {
                    this.PartidaField = value;
                    this.RaisePropertyChanged("Partida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuadricula {
            get {
                return this.cuadriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuadriculaField, value) != true)) {
                    this.cuadriculaField = value;
                    this.RaisePropertyChanged("cuadricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short no_casillas {
            get {
                return this.no_casillasField;
            }
            set {
                if ((this.no_casillasField.Equals(value) != true)) {
                    this.no_casillasField = value;
                    this.RaisePropertyChanged("no_casillas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Casilla", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Casilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Portal PortalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Tablero TableroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TableroIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool especialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Portal Portal {
            get {
                return this.PortalField;
            }
            set {
                if ((object.ReferenceEquals(this.PortalField, value) != true)) {
                    this.PortalField = value;
                    this.RaisePropertyChanged("Portal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Tablero Tablero {
            get {
                return this.TableroField;
            }
            set {
                if ((object.ReferenceEquals(this.TableroField, value) != true)) {
                    this.TableroField = value;
                    this.RaisePropertyChanged("Tablero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TableroId {
            get {
                return this.TableroIdField;
            }
            set {
                if ((this.TableroIdField.Equals(value) != true)) {
                    this.TableroIdField = value;
                    this.RaisePropertyChanged("TableroId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool especial {
            get {
                return this.especialField;
            }
            set {
                if ((this.especialField.Equals(value) != true)) {
                    this.especialField = value;
                    this.RaisePropertyChanged("especial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ficha", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Ficha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Tablero TableroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Tablero Tablero {
            get {
                return this.TableroField;
            }
            set {
                if ((object.ReferenceEquals(this.TableroField, value) != true)) {
                    this.TableroField = value;
                    this.RaisePropertyChanged("Tablero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FondoTablero", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class FondoTablero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Tablero TableroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Tablero Tablero {
            get {
                return this.TableroField;
            }
            set {
                if ((object.ReferenceEquals(this.TableroField, value) != true)) {
                    this.TableroField = value;
                    this.RaisePropertyChanged("Tablero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Portal", Namespace="http://schemas.datacontract.org/2004/07/DAO")]
    [System.SerializableAttribute()]
    public partial class Portal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServiceReference2.Casilla CasillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServiceReference2.Casilla Casilla {
            get {
                return this.CasillaField;
            }
            set {
                if ((object.ReferenceEquals(this.CasillaField, value) != true)) {
                    this.CasillaField = value;
                    this.RaisePropertyChanged("Casilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IAdministradorCuenta")]
    public interface IAdministradorCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IAdministradorCuenta/IniciarSesionResponse")]
        bool IniciarSesion(SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IAdministradorCuenta/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/RegistrarJugadorResponse")]
        bool RegistrarJugador(SerpientesEscaleras.ServiceReference2.Jugador jugador, SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(SerpientesEscaleras.ServiceReference2.Jugador jugador, SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugadorResponse")]
        bool ActivarCuentaJugador(SerpientesEscaleras.ServiceReference2.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugadorResponse")]
        System.Threading.Tasks.Task<bool> ActivarCuentaJugadorAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarCuentaResponse")]
        bool VerificarCuenta(SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarCuentaResponse")]
        System.Threading.Tasks.Task<bool> VerificarCuentaAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IAdministradorCuenta/EnviarCorreoResponse")]
        bool EnviarCorreo(SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IAdministradorCuenta/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<bool> EnviarCorreoAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropiosResponse")]
        SerpientesEscaleras.ServiceReference2.Puntuacion[] ConsultarPuntajesPropios(SerpientesEscaleras.ServiceReference2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropiosResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServiceReference2.Puntuacion[]> ConsultarPuntajesPropiosAsync(SerpientesEscaleras.ServiceReference2.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajesResponse")]
        SerpientesEscaleras.ServiceReference2.Puntuacion[] ConsultarMejoresPuntajes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajesResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServiceReference2.Puntuacion[]> ConsultarMejoresPuntajesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorCuentaChannel : SerpientesEscaleras.ServiceReference2.IAdministradorCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorCuentaClient : System.ServiceModel.ClientBase<SerpientesEscaleras.ServiceReference2.IAdministradorCuenta>, SerpientesEscaleras.ServiceReference2.IAdministradorCuenta {
        
        public AdministradorCuentaClient() {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IniciarSesion(SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.IniciarSesion(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.IniciarSesionAsync(cuenta);
        }
        
        public bool RegistrarJugador(SerpientesEscaleras.ServiceReference2.Jugador jugador, SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.RegistrarJugador(jugador, cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(SerpientesEscaleras.ServiceReference2.Jugador jugador, SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.RegistrarJugadorAsync(jugador, cuenta);
        }
        
        public bool ActivarCuentaJugador(SerpientesEscaleras.ServiceReference2.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugador(cuenta, codigo);
        }
        
        public System.Threading.Tasks.Task<bool> ActivarCuentaJugadorAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugadorAsync(cuenta, codigo);
        }
        
        public bool VerificarCuenta(SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.VerificarCuenta(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarCuentaAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.VerificarCuentaAsync(cuenta);
        }
        
        public bool EnviarCorreo(SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.EnviarCorreo(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCorreoAsync(SerpientesEscaleras.ServiceReference2.Cuenta cuenta) {
            return base.Channel.EnviarCorreoAsync(cuenta);
        }
        
        public SerpientesEscaleras.ServiceReference2.Puntuacion[] ConsultarPuntajesPropios(SerpientesEscaleras.ServiceReference2.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropios(jugador);
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServiceReference2.Puntuacion[]> ConsultarPuntajesPropiosAsync(SerpientesEscaleras.ServiceReference2.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropiosAsync(jugador);
        }
        
        public SerpientesEscaleras.ServiceReference2.Puntuacion[] ConsultarMejoresPuntajes() {
            return base.Channel.ConsultarMejoresPuntajes();
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServiceReference2.Puntuacion[]> ConsultarMejoresPuntajesAsync() {
            return base.Channel.ConsultarMejoresPuntajesAsync();
        }
    }
}
