//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesEscaleras.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISerpientesEscalerasServicio")]
    public interface ISerpientesEscalerasServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerpientesEscalerasServicio/DoWork", ReplyAction="http://tempuri.org/ISerpientesEscalerasServicio/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerpientesEscalerasServicio/DoWork", ReplyAction="http://tempuri.org/ISerpientesEscalerasServicio/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerpientesEscalerasServicio/IniciarSesion", ReplyAction="http://tempuri.org/ISerpientesEscalerasServicio/IniciarSesionResponse")]
        bool IniciarSesion(SerpientesEscaleras.ServiceReference1.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerpientesEscalerasServicio/IniciarSesion", ReplyAction="http://tempuri.org/ISerpientesEscalerasServicio/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(SerpientesEscaleras.ServiceReference1.Cuenta cuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISerpientesEscalerasServicioChannel : SerpientesEscaleras.ServiceReference1.ISerpientesEscalerasServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerpientesEscalerasServicioClient : System.ServiceModel.ClientBase<SerpientesEscaleras.ServiceReference1.ISerpientesEscalerasServicio>, SerpientesEscaleras.ServiceReference1.ISerpientesEscalerasServicio {
        
        public SerpientesEscalerasServicioClient() {
        }
        
        public SerpientesEscalerasServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerpientesEscalerasServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerpientesEscalerasServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerpientesEscalerasServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool IniciarSesion(SerpientesEscaleras.ServiceReference1.Cuenta cuenta) {
            return base.Channel.IniciarSesion(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(SerpientesEscaleras.ServiceReference1.Cuenta cuenta) {
            return base.Channel.IniciarSesionAsync(cuenta);
        }
    }
}
