//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesEscaleras.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SerpientesEscaleras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string apodo {
            get {
                return ResourceManager.GetString("apodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Partida.
        /// </summary>
        public static string buscarPartida {
            get {
                return ResourceManager.GetString("buscarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string confirmarContrasenia {
            get {
                return ResourceManager.GetString("confirmarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Puntajes.
        /// </summary>
        public static string consultarPuntajes {
            get {
                return ResourceManager.GetString("consultarPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string contrasenia {
            get {
                return ResourceManager.GetString("contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo eléctronico.
        /// </summary>
        public static string correoElectronico {
            get {
                return ResourceManager.GetString("correoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado a su correo el codigo de activación de su cuenta..
        /// </summary>
        public static string correoEnviado {
            get {
                return ResourceManager.GetString("correoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string crearPartida {
            get {
                return ResourceManager.GetString("crearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Cuenta.
        /// </summary>
        public static string datosCuenta {
            get {
                return ResourceManager.GetString("datosCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string datosPersonales {
            get {
                return ResourceManager.GetString("datosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a la partida.
        /// </summary>
        public static string entrarPartida {
            get {
                return ResourceManager.GetString("entrarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string idiomaEncabezado {
            get {
                return ResourceManager.GetString("idiomaEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string idiomaEspañol {
            get {
                return ResourceManager.GetString("idiomaEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string idiomaIngles {
            get {
                return ResourceManager.GetString("idiomaIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar código.
        /// </summary>
        public static string ingresarCodigo {
            get {
                return ResourceManager.GetString("ingresarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor de ingresar un código.
        /// </summary>
        public static string ingresarCodigoVacio {
            get {
                return ResourceManager.GetString("ingresarCodigoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string iniciarSesion {
            get {
                return ResourceManager.GetString("iniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  de 4 jugadores conectados.
        /// </summary>
        public static string jugadoresConectados {
            get {
                return ResourceManager.GetString("jugadoresConectados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores Puntajes.
        /// </summary>
        public static string mejoresPuntajes {
            get {
                return ResourceManager.GetString("mejoresPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se unió a la partida.
        /// </summary>
        public static string mensajeEntrada {
            get {
                return ResourceManager.GetString("mensajeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a salió de la partida.
        /// </summary>
        public static string mensajeSalida {
            get {
                return ResourceManager.GetString("mensajeSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor de ingresar información en todos los campos.
        /// </summary>
        public static string mensajeValidacion {
            get {
                return ResourceManager.GetString("mensajeValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis puntajes.
        /// </summary>
        public static string misPuntajes {
            get {
                return ResourceManager.GetString("misPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Partida.
        /// </summary>
        public static string nuevaPartida {
            get {
                return ResourceManager.GetString("nuevaPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar correo.
        /// </summary>
        public static string reenviarCorreo {
            get {
                return ResourceManager.GetString("reenviarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string registrar {
            get {
                return ResourceManager.GetString("registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de usuario.
        /// </summary>
        public static string registroUsuario {
            get {
                return ResourceManager.GetString("registroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string regresar {
            get {
                return ResourceManager.GetString("regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string salir {
            get {
                return ResourceManager.GetString("salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir del juego.
        /// </summary>
        public static string salirJuego {
            get {
                return ResourceManager.GetString("salirJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serpientes y Escaleras.
        /// </summary>
        public static string serpientesEscaleras {
            get {
                return ResourceManager.GetString("serpientesEscaleras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string textBlockSinCuenta {
            get {
                return ResourceManager.GetString("textBlockSinCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar cuenta.
        /// </summary>
        public static string validarCuenta {
            get {
                return ResourceManager.GetString("validarCuenta", resourceCulture);
            }
        }
    }
}
