//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesEscaleras.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SerpientesEscaleras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string apodo {
            get {
                return ResourceManager.GetString("apodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Partida.
        /// </summary>
        public static string buscarPartida {
            get {
                return ResourceManager.GetString("buscarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos son obligatorios.
        /// </summary>
        public static string camposObligatorios {
            get {
                return ResourceManager.GetString("camposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casillas especiales.
        /// </summary>
        public static string casillaEspecial {
            get {
                return ResourceManager.GetString("casillaEspecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código no válido.
        /// </summary>
        public static string codigoInvalido {
            get {
                return ResourceManager.GetString("codigoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string confirmarContrasenia {
            get {
                return ResourceManager.GetString("confirmarContrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Puntajes.
        /// </summary>
        public static string consultarPuntajes {
            get {
                return ResourceManager.GetString("consultarPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no coincide.
        /// </summary>
        public static string contraseñaNoCoincide {
            get {
                return ResourceManager.GetString("contraseñaNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string contrasenia {
            get {
                return ResourceManager.GetString("contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo eléctronico.
        /// </summary>
        public static string correoElectronico {
            get {
                return ResourceManager.GetString("correoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado a su correo el codigo de activación de su cuenta..
        /// </summary>
        public static string correoEnviado {
            get {
                return ResourceManager.GetString("correoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo inválido..
        /// </summary>
        public static string correoInvalido {
            get {
                return ResourceManager.GetString("correoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ya se encuentra registrado.
        /// </summary>
        public static string correoRepetido {
            get {
                return ResourceManager.GetString("correoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string crearPartida {
            get {
                return ResourceManager.GetString("crearPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta activada exitosamente.
        /// </summary>
        public static string cuentaActivada {
            get {
                return ResourceManager.GetString("cuentaActivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Cuenta.
        /// </summary>
        public static string datosCuenta {
            get {
                return ResourceManager.GetString("datosCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string datosPersonales {
            get {
                return ResourceManager.GetString("datosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble dado.
        /// </summary>
        public static string dobleDado {
            get {
                return ResourceManager.GetString("dobleDado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble ficha de jugador.
        /// </summary>
        public static string dobleFicha {
            get {
                return ResourceManager.GetString("dobleFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primero elige una partida.
        /// </summary>
        public static string elegirPartida {
            get {
                return ResourceManager.GetString("elegirPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a la partida.
        /// </summary>
        public static string entrarPartida {
            get {
                return ResourceManager.GetString("entrarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con la base de datos. Intente de nuevo más tarde..
        /// </summary>
        public static string errorConexionBaseDatos {
            get {
                return ResourceManager.GetString("errorConexionBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor. Verifique su conexión a internet o intente más tarde..
        /// </summary>
        public static string errorConexionServidor {
            get {
                return ResourceManager.GetString("errorConexionServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al mandar su correo de activación. Verifique que su correo sea correcto..
        /// </summary>
        public static string errorMandarCorreo {
            get {
                return ResourceManager.GetString("errorMandarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando jugadores.
        /// </summary>
        public static string esperandoJugadores {
            get {
                return ResourceManager.GetString("esperandoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string idiomaEncabezado {
            get {
                return ResourceManager.GetString("idiomaEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string idiomaEspañol {
            get {
                return ResourceManager.GetString("idiomaEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string idiomaIngles {
            get {
                return ResourceManager.GetString("idiomaIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa una contraseña.
        /// </summary>
        public static string ingresaContraseña {
            get {
                return ResourceManager.GetString("ingresaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar código.
        /// </summary>
        public static string ingresarCodigo {
            get {
                return ResourceManager.GetString("ingresarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de activación.
        /// </summary>
        public static string ingresarCodigoActivacion {
            get {
                return ResourceManager.GetString("ingresarCodigoActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor de ingresar un código.
        /// </summary>
        public static string ingresarCodigoVacio {
            get {
                return ResourceManager.GetString("ingresarCodigoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un usuario.
        /// </summary>
        public static string ingresaUsuario {
            get {
                return ResourceManager.GetString("ingresaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string iniciarSesion {
            get {
                return ResourceManager.GetString("iniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  de 4 jugadores conectados.
        /// </summary>
        public static string jugadoresConectados {
            get {
                return ResourceManager.GetString("jugadoresConectados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya está llena.
        /// </summary>
        public static string llena {
            get {
                return ResourceManager.GetString("llena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores Puntajes.
        /// </summary>
        public static string mejoresPuntajes {
            get {
                return ResourceManager.GetString("mejoresPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se unió a la partida.
        /// </summary>
        public static string mensajeEntrada {
            get {
                return ResourceManager.GetString("mensajeEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a salió de la partida.
        /// </summary>
        public static string mensajeSalida {
            get {
                return ResourceManager.GetString("mensajeSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor de ingresar información en todos los campos.
        /// </summary>
        public static string mensajeValidacion {
            get {
                return ResourceManager.GetString("mensajeValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis puntajes.
        /// </summary>
        public static string misPuntajes {
            get {
                return ResourceManager.GetString("misPuntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la partida.
        /// </summary>
        public static string nombrePartida {
            get {
                return ResourceManager.GetString("nombrePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Partida.
        /// </summary>
        public static string nuevaPartida {
            get {
                return ResourceManager.GetString("nuevaPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. de jugadores conectados.
        /// </summary>
        public static string numJugadores {
            get {
                return ResourceManager.GetString("numJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida.
        /// </summary>
        public static string partida {
            get {
                return ResourceManager.GetString("partida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar correo.
        /// </summary>
        public static string reenviarCorreo {
            get {
                return ResourceManager.GetString("reenviarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string registrar {
            get {
                return ResourceManager.GetString("registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de usuario.
        /// </summary>
        public static string registroUsuario {
            get {
                return ResourceManager.GetString("registroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas especiales.
        /// </summary>
        public static string reglasEspeciales {
            get {
                return ResourceManager.GetString("reglasEspeciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string regresar {
            get {
                return ResourceManager.GetString("regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string salir {
            get {
                return ResourceManager.GetString("salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir del juego.
        /// </summary>
        public static string salirJuego {
            get {
                return ResourceManager.GetString("salirJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serpientes y Escaleras.
        /// </summary>
        public static string serpientesEscaleras {
            get {
                return ResourceManager.GetString("serpientesEscaleras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string textBlockSinCuenta {
            get {
                return ResourceManager.GetString("textBlockSinCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string tituloErrorConexion {
            get {
                return ResourceManager.GetString("tituloErrorConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y/o contraseña no es correcto.
        /// </summary>
        public static string usuarioContraseñaInvalidas {
            get {
                return ResourceManager.GetString("usuarioContraseñaInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se encuentra registrado un usuario con ese apodo.
        /// </summary>
        public static string usuarioRepetido {
            get {
                return ResourceManager.GetString("usuarioRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar cuenta.
        /// </summary>
        public static string validarCuenta {
            get {
                return ResourceManager.GetString("validarCuenta", resourceCulture);
            }
        }
    }
}
