//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesEscaleras.ServidorJuegoSE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaTablaPuntajes", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class FilaTablaPuntajes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntos {
            get {
                return this.PuntosField;
            }
            set {
                if ((this.PuntosField.Equals(value) != true)) {
                    this.PuntosField = value;
                    this.RaisePropertyChanged("Puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Turnos {
            get {
                return this.TurnosField;
            }
            set {
                if ((this.TurnosField.Equals(value) != true)) {
                    this.TurnosField = value;
                    this.RaisePropertyChanged("Turnos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sala", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Sala : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CasillasEspecialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, SerpientesEscaleras.ServidorJuegoSE.Jugador> DiccionarioJugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DobleDadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DobleFichaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool JugandoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumJugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriFondoTableroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CasillasEspeciales {
            get {
                return this.CasillasEspecialesField;
            }
            set {
                if ((this.CasillasEspecialesField.Equals(value) != true)) {
                    this.CasillasEspecialesField = value;
                    this.RaisePropertyChanged("CasillasEspeciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, SerpientesEscaleras.ServidorJuegoSE.Jugador> DiccionarioJugadores {
            get {
                return this.DiccionarioJugadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioJugadoresField, value) != true)) {
                    this.DiccionarioJugadoresField = value;
                    this.RaisePropertyChanged("DiccionarioJugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DobleDado {
            get {
                return this.DobleDadoField;
            }
            set {
                if ((this.DobleDadoField.Equals(value) != true)) {
                    this.DobleDadoField = value;
                    this.RaisePropertyChanged("DobleDado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DobleFicha {
            get {
                return this.DobleFichaField;
            }
            set {
                if ((this.DobleFichaField.Equals(value) != true)) {
                    this.DobleFichaField = value;
                    this.RaisePropertyChanged("DobleFicha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSala {
            get {
                return this.IdSalaField;
            }
            set {
                if ((this.IdSalaField.Equals(value) != true)) {
                    this.IdSalaField = value;
                    this.RaisePropertyChanged("IdSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Jugando {
            get {
                return this.JugandoField;
            }
            set {
                if ((this.JugandoField.Equals(value) != true)) {
                    this.JugandoField = value;
                    this.RaisePropertyChanged("Jugando");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumJugadores {
            get {
                return this.NumJugadoresField;
            }
            set {
                if ((this.NumJugadoresField.Equals(value) != true)) {
                    this.NumJugadoresField = value;
                    this.RaisePropertyChanged("NumJugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UriFondoTablero {
            get {
                return this.UriFondoTableroField;
            }
            set {
                if ((object.ReferenceEquals(this.UriFondoTableroField, value) != true)) {
                    this.UriFondoTableroField = value;
                    this.RaisePropertyChanged("UriFondoTablero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorJuegoSE.IAdministradorCuenta")]
    public interface IAdministradorCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IAdministradorCuenta/IniciarSesionResponse")]
        SerpientesEscaleras.ServidorJuegoSE.Jugador IniciarSesion(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IAdministradorCuenta/IniciarSesionResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Jugador> IniciarSesionAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/RegistrarJugadorResponse")]
        bool RegistrarJugador(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugadorResponse")]
        bool ActivarCuentaJugador(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugadorResponse")]
        System.Threading.Tasks.Task<bool> ActivarCuentaJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarCuentaResponse")]
        bool VerificarCuenta(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarCuentaResponse")]
        System.Threading.Tasks.Task<bool> VerificarCuentaAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarApodo", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarApodoResponse")]
        bool VerificarApodo(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarApodo", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarApodoResponse")]
        System.Threading.Tasks.Task<bool> VerificarApodoAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IAdministradorCuenta/EnviarCorreoResponse")]
        bool EnviarCorreo(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IAdministradorCuenta/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<bool> EnviarCorreoAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropiosResponse")]
        SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarPuntajesPropios(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropiosResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarPuntajesPropiosAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajesResponse")]
        SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarMejoresPuntajes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajesResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarMejoresPuntajesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorCuentaChannel : SerpientesEscaleras.ServidorJuegoSE.IAdministradorCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorCuentaClient : System.ServiceModel.ClientBase<SerpientesEscaleras.ServidorJuegoSE.IAdministradorCuenta>, SerpientesEscaleras.ServidorJuegoSE.IAdministradorCuenta {
        
        public AdministradorCuentaClient() {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.Jugador IniciarSesion(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.IniciarSesion(cuenta);
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Jugador> IniciarSesionAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.IniciarSesionAsync(cuenta);
        }
        
        public bool RegistrarJugador(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.RegistrarJugador(jugador, cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.RegistrarJugadorAsync(jugador, cuenta);
        }
        
        public bool ActivarCuentaJugador(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugador(cuenta, codigo);
        }
        
        public System.Threading.Tasks.Task<bool> ActivarCuentaJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugadorAsync(cuenta, codigo);
        }
        
        public bool VerificarCuenta(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.VerificarCuenta(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarCuentaAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.VerificarCuentaAsync(cuenta);
        }
        
        public bool VerificarApodo(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.VerificarApodo(jugador);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarApodoAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.VerificarApodoAsync(jugador);
        }
        
        public bool EnviarCorreo(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.EnviarCorreo(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCorreoAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.EnviarCorreoAsync(cuenta);
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarPuntajesPropios(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropios(jugador);
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarPuntajesPropiosAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropiosAsync(jugador);
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarMejoresPuntajes() {
            return base.Channel.ConsultarMejoresPuntajes();
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarMejoresPuntajesAsync() {
            return base.Channel.ConsultarMejoresPuntajesAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorJuegoSE.IAdministradorMultijugador", CallbackContract=typeof(SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugadorCallback))]
    public interface IAdministradorMultijugador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/CrearSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/CrearSalaResponse")]
        int CrearSala(SerpientesEscaleras.ServidorJuegoSE.Sala sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/CrearSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/CrearSalaResponse")]
        System.Threading.Tasks.Task<int> CrearSalaAsync(SerpientesEscaleras.ServidorJuegoSE.Sala sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponibles", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponiblesResponse")]
        SerpientesEscaleras.ServidorJuegoSE.Sala[] ConsultarSalasDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponibles", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponiblesResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Sala[]> ConsultarSalasDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSalaResponse")]
        string[] ConsultarJugadoresSala(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSalaResponse")]
        System.Threading.Tasks.Task<string[]> ConsultarJugadoresSalaAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/UnirseSala")]
        void UnirseSala(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/UnirseSala")]
        System.Threading.Tasks.Task UnirseSalaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ValidarSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ValidarSalaResponse")]
        bool ValidarSala(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ValidarSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ValidarSalaResponse")]
        System.Threading.Tasks.Task<bool> ValidarSalaAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EnviarMensaje")]
        void EnviarMensaje(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirChat")]
        void SalirChat(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirChat")]
        System.Threading.Tasks.Task SalirChatAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/IniciarJuego")]
        void IniciarJuego(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/IniciarJuego")]
        System.Threading.Tasks.Task IniciarJuegoAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirJuego")]
        void SalirJuego(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirJuego")]
        System.Threading.Tasks.Task SalirJuegoAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ObtenerFondo", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ObtenerFondoResponse")]
        string ObtenerFondo(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ObtenerFondo", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ObtenerFondoResponse")]
        System.Threading.Tasks.Task<string> ObtenerFondoAsync(int idSala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorMultijugadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirMensaje")]
        void RecibirMensaje(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirMensajeMiembro")]
        void RecibirMensajeMiembro(bool entrada, string apodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EntrarJuego")]
        void EntrarJuego();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorMultijugadorChannel : SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorMultijugadorClient : System.ServiceModel.DuplexClientBase<SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugador>, SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugador {
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int CrearSala(SerpientesEscaleras.ServidorJuegoSE.Sala sala) {
            return base.Channel.CrearSala(sala);
        }
        
        public System.Threading.Tasks.Task<int> CrearSalaAsync(SerpientesEscaleras.ServidorJuegoSE.Sala sala) {
            return base.Channel.CrearSalaAsync(sala);
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.Sala[] ConsultarSalasDisponibles() {
            return base.Channel.ConsultarSalasDisponibles();
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Sala[]> ConsultarSalasDisponiblesAsync() {
            return base.Channel.ConsultarSalasDisponiblesAsync();
        }
        
        public string[] ConsultarJugadoresSala(int idSala) {
            return base.Channel.ConsultarJugadoresSala(idSala);
        }
        
        public System.Threading.Tasks.Task<string[]> ConsultarJugadoresSalaAsync(int idSala) {
            return base.Channel.ConsultarJugadoresSalaAsync(idSala);
        }
        
        public void UnirseSala(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            base.Channel.UnirseSala(idSala, jugador);
        }
        
        public System.Threading.Tasks.Task UnirseSalaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.UnirseSalaAsync(idSala, jugador);
        }
        
        public bool ValidarSala(int idSala) {
            return base.Channel.ValidarSala(idSala);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarSalaAsync(int idSala) {
            return base.Channel.ValidarSalaAsync(idSala);
        }
        
        public void EnviarMensaje(int idSala, string mensaje) {
            base.Channel.EnviarMensaje(idSala, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(int idSala, string mensaje) {
            return base.Channel.EnviarMensajeAsync(idSala, mensaje);
        }
        
        public void SalirChat(int idSala) {
            base.Channel.SalirChat(idSala);
        }
        
        public System.Threading.Tasks.Task SalirChatAsync(int idSala) {
            return base.Channel.SalirChatAsync(idSala);
        }
        
        public void IniciarJuego(int idSala) {
            base.Channel.IniciarJuego(idSala);
        }
        
        public System.Threading.Tasks.Task IniciarJuegoAsync(int idSala) {
            return base.Channel.IniciarJuegoAsync(idSala);
        }
        
        public void SalirJuego(int idSala) {
            base.Channel.SalirJuego(idSala);
        }
        
        public System.Threading.Tasks.Task SalirJuegoAsync(int idSala) {
            return base.Channel.SalirJuegoAsync(idSala);
        }
        
        public string ObtenerFondo(int idSala) {
            return base.Channel.ObtenerFondo(idSala);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerFondoAsync(int idSala) {
            return base.Channel.ObtenerFondoAsync(idSala);
        }
    }
}
