//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerpientesEscaleras.ServidorJuegoSE {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Validada {
            get {
                return this.ValidadaField;
            }
            set {
                if ((this.ValidadaField.Equals(value) != true)) {
                    this.ValidadaField = value;
                    this.RaisePropertyChanged("Validada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaTablaPuntajes", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class FilaTablaPuntajes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TurnosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntos {
            get {
                return this.PuntosField;
            }
            set {
                if ((this.PuntosField.Equals(value) != true)) {
                    this.PuntosField = value;
                    this.RaisePropertyChanged("Puntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Turnos {
            get {
                return this.TurnosField;
            }
            set {
                if ((this.TurnosField.Equals(value) != true)) {
                    this.TurnosField = value;
                    this.RaisePropertyChanged("Turnos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sala", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Sala : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CasillasEspecialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, SerpientesEscaleras.ServidorJuegoSE.Jugador> DiccionarioJugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<object, SerpientesEscaleras.ServidorJuegoSE.Jugador> DiccionarioJugadoresLobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DobleDadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DobleFichaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SerpientesEscaleras.ServidorJuegoSE.Ficha[] FichasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JugadorEnTurnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] JugadoresJugandoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool JugandoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumJugadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriFondoTableroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CasillasEspeciales {
            get {
                return this.CasillasEspecialesField;
            }
            set {
                if ((this.CasillasEspecialesField.Equals(value) != true)) {
                    this.CasillasEspecialesField = value;
                    this.RaisePropertyChanged("CasillasEspeciales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, SerpientesEscaleras.ServidorJuegoSE.Jugador> DiccionarioJugadores {
            get {
                return this.DiccionarioJugadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioJugadoresField, value) != true)) {
                    this.DiccionarioJugadoresField = value;
                    this.RaisePropertyChanged("DiccionarioJugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<object, SerpientesEscaleras.ServidorJuegoSE.Jugador> DiccionarioJugadoresLobby {
            get {
                return this.DiccionarioJugadoresLobbyField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioJugadoresLobbyField, value) != true)) {
                    this.DiccionarioJugadoresLobbyField = value;
                    this.RaisePropertyChanged("DiccionarioJugadoresLobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DobleDado {
            get {
                return this.DobleDadoField;
            }
            set {
                if ((this.DobleDadoField.Equals(value) != true)) {
                    this.DobleDadoField = value;
                    this.RaisePropertyChanged("DobleDado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DobleFicha {
            get {
                return this.DobleFichaField;
            }
            set {
                if ((this.DobleFichaField.Equals(value) != true)) {
                    this.DobleFichaField = value;
                    this.RaisePropertyChanged("DobleFicha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SerpientesEscaleras.ServidorJuegoSE.Ficha[] Fichas {
            get {
                return this.FichasField;
            }
            set {
                if ((object.ReferenceEquals(this.FichasField, value) != true)) {
                    this.FichasField = value;
                    this.RaisePropertyChanged("Fichas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSala {
            get {
                return this.IdSalaField;
            }
            set {
                if ((this.IdSalaField.Equals(value) != true)) {
                    this.IdSalaField = value;
                    this.RaisePropertyChanged("IdSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JugadorEnTurno {
            get {
                return this.JugadorEnTurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorEnTurnoField, value) != true)) {
                    this.JugadorEnTurnoField = value;
                    this.RaisePropertyChanged("JugadorEnTurno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] JugadoresJugando {
            get {
                return this.JugadoresJugandoField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadoresJugandoField, value) != true)) {
                    this.JugadoresJugandoField = value;
                    this.RaisePropertyChanged("JugadoresJugando");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Jugando {
            get {
                return this.JugandoField;
            }
            set {
                if ((this.JugandoField.Equals(value) != true)) {
                    this.JugandoField = value;
                    this.RaisePropertyChanged("Jugando");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumJugadores {
            get {
                return this.NumJugadoresField;
            }
            set {
                if ((this.NumJugadoresField.Equals(value) != true)) {
                    this.NumJugadoresField = value;
                    this.RaisePropertyChanged("NumJugadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UriFondoTablero {
            get {
                return this.UriFondoTableroField;
            }
            set {
                if ((object.ReferenceEquals(this.UriFondoTableroField, value) != true)) {
                    this.UriFondoTableroField = value;
                    this.RaisePropertyChanged("UriFondoTablero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ficha", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Ficha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFichaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriFichaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApodoJugador {
            get {
                return this.ApodoJugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoJugadorField, value) != true)) {
                    this.ApodoJugadorField = value;
                    this.RaisePropertyChanged("ApodoJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicha {
            get {
                return this.NombreFichaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFichaField, value) != true)) {
                    this.NombreFichaField = value;
                    this.RaisePropertyChanged("NombreFicha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((this.PosicionField.Equals(value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UriFicha {
            get {
                return this.UriFichaField;
            }
            set {
                if ((object.ReferenceEquals(this.UriFichaField, value) != true)) {
                    this.UriFichaField = value;
                    this.RaisePropertyChanged("UriFicha");
                }
            }
        }

        public int Movimientos { get; internal set; }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Casilla", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Casilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EspecialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Columna {
            get {
                return this.ColumnaField;
            }
            set {
                if ((this.ColumnaField.Equals(value) != true)) {
                    this.ColumnaField = value;
                    this.RaisePropertyChanged("Columna");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Especial {
            get {
                return this.EspecialField;
            }
            set {
                if ((this.EspecialField.Equals(value) != true)) {
                    this.EspecialField = value;
                    this.RaisePropertyChanged("Especial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fila {
            get {
                return this.FilaField;
            }
            set {
                if ((this.FilaField.Equals(value) != true)) {
                    this.FilaField = value;
                    this.RaisePropertyChanged("Fila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Portal", Namespace="http://schemas.datacontract.org/2004/07/MessageService")]
    [System.SerializableAttribute()]
    public partial class Portal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCasillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriPortalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonaTableroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCasilla {
            get {
                return this.IdCasillaField;
            }
            set {
                if ((this.IdCasillaField.Equals(value) != true)) {
                    this.IdCasillaField = value;
                    this.RaisePropertyChanged("IdCasilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UriPortal {
            get {
                return this.UriPortalField;
            }
            set {
                if ((object.ReferenceEquals(this.UriPortalField, value) != true)) {
                    this.UriPortalField = value;
                    this.RaisePropertyChanged("UriPortal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZonaTablero {
            get {
                return this.ZonaTableroField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonaTableroField, value) != true)) {
                    this.ZonaTableroField = value;
                    this.RaisePropertyChanged("ZonaTablero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorJuegoSE.IAdministradorCuenta")]
    public interface IAdministradorCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IAdministradorCuenta/IniciarSesionResponse")]
        SerpientesEscaleras.ServidorJuegoSE.Jugador IniciarSesion(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/IniciarSesion", ReplyAction="http://tempuri.org/IAdministradorCuenta/IniciarSesionResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Jugador> IniciarSesionAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/RegistrarJugadorResponse")]
        int RegistrarJugador(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/RegistrarJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/RegistrarJugadorResponse")]
        System.Threading.Tasks.Task<int> RegistrarJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugadorResponse")]
        int ActivarCuentaJugador(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugador", ReplyAction="http://tempuri.org/IAdministradorCuenta/ActivarCuentaJugadorResponse")]
        System.Threading.Tasks.Task<int> ActivarCuentaJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarCuentaResponse")]
        SerpientesEscaleras.ServidorJuegoSE.Cuenta VerificarCuenta(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/VerificarCuenta", ReplyAction="http://tempuri.org/IAdministradorCuenta/VerificarCuentaResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Cuenta> VerificarCuentaAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IAdministradorCuenta/EnviarCorreoResponse")]
        int EnviarCorreo(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/EnviarCorreo", ReplyAction="http://tempuri.org/IAdministradorCuenta/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<int> EnviarCorreoAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropiosResponse")]
        SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarPuntajesPropios(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropios", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarPuntajesPropiosResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarPuntajesPropiosAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajesResponse")]
        SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarMejoresPuntajes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajes", ReplyAction="http://tempuri.org/IAdministradorCuenta/ConsultarMejoresPuntajesResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarMejoresPuntajesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorCuentaChannel : SerpientesEscaleras.ServidorJuegoSE.IAdministradorCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorCuentaClient : System.ServiceModel.ClientBase<SerpientesEscaleras.ServidorJuegoSE.IAdministradorCuenta>, SerpientesEscaleras.ServidorJuegoSE.IAdministradorCuenta {
        
        public AdministradorCuentaClient() {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.Jugador IniciarSesion(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.IniciarSesion(cuenta);
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Jugador> IniciarSesionAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.IniciarSesionAsync(cuenta);
        }
        
        public int RegistrarJugador(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.RegistrarJugador(jugador, cuenta);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador, SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.RegistrarJugadorAsync(jugador, cuenta);
        }
        
        public int ActivarCuentaJugador(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugador(cuenta, codigo);
        }
        
        public System.Threading.Tasks.Task<int> ActivarCuentaJugadorAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta, string codigo) {
            return base.Channel.ActivarCuentaJugadorAsync(cuenta, codigo);
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.Cuenta VerificarCuenta(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.VerificarCuenta(cuenta);
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Cuenta> VerificarCuentaAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.VerificarCuentaAsync(cuenta);
        }
        
        public int EnviarCorreo(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.EnviarCorreo(cuenta);
        }
        
        public System.Threading.Tasks.Task<int> EnviarCorreoAsync(SerpientesEscaleras.ServidorJuegoSE.Cuenta cuenta) {
            return base.Channel.EnviarCorreoAsync(cuenta);
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarPuntajesPropios(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropios(jugador);
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarPuntajesPropiosAsync(SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.ConsultarPuntajesPropiosAsync(jugador);
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[] ConsultarMejoresPuntajes() {
            return base.Channel.ConsultarMejoresPuntajes();
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.FilaTablaPuntajes[]> ConsultarMejoresPuntajesAsync() {
            return base.Channel.ConsultarMejoresPuntajesAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorJuegoSE.IAdministradorMultijugador", CallbackContract=typeof(SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugadorCallback))]
    public interface IAdministradorMultijugador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/CrearSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/CrearSalaResponse")]
        int CrearSala(SerpientesEscaleras.ServidorJuegoSE.Sala sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/CrearSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/CrearSalaResponse")]
        System.Threading.Tasks.Task<int> CrearSalaAsync(SerpientesEscaleras.ServidorJuegoSE.Sala sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponibles", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponiblesResponse")]
        SerpientesEscaleras.ServidorJuegoSE.Sala[] ConsultarSalasDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponibles", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarSalasDisponiblesResponse")]
        System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Sala[]> ConsultarSalasDisponiblesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSalaResponse")]
        string[] ConsultarJugadoresSala(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ConsultarJugadoresSalaResponse")]
        System.Threading.Tasks.Task<string[]> ConsultarJugadoresSalaAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/UnirseSala")]
        void UnirseSala(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/UnirseSala")]
        System.Threading.Tasks.Task UnirseSalaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ValidarSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ValidarSalaResponse")]
        bool ValidarSala(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministradorMultijugador/ValidarSala", ReplyAction="http://tempuri.org/IAdministradorMultijugador/ValidarSalaResponse")]
        System.Threading.Tasks.Task<bool> ValidarSalaAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EnviarMensaje")]
        void EnviarMensaje(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirChat")]
        void SalirChat(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirChat")]
        System.Threading.Tasks.Task SalirChatAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/IniciarJuego")]
        void IniciarJuego(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/IniciarJuego")]
        System.Threading.Tasks.Task IniciarJuegoAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/UnirseJuego")]
        void UnirseJuego(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/UnirseJuego")]
        System.Threading.Tasks.Task UnirseJuegoAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EnviarMensajeJuego")]
        void EnviarMensajeJuego(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EnviarMensajeJuego")]
        System.Threading.Tasks.Task EnviarMensajeJuegoAsync(int idSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirJuego")]
        void SalirJuego(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SalirJuego")]
        System.Threading.Tasks.Task SalirJuegoAsync(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/AsignarFicha")]
        void AsignarFicha(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/AsignarFicha")]
        System.Threading.Tasks.Task AsignarFichaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirTiro")]
        void RecibirTiro(int idSala, int numDado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirTiro")]
        System.Threading.Tasks.Task RecibirTiroAsync(int idSala, int numDado);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/CambiarPosicionFicha")]
        void CambiarPosicionFicha(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/CambiarPosicionFicha")]
        System.Threading.Tasks.Task CambiarPosicionFichaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/CambiarPortales")]
        void CambiarPortales(int idSala, SerpientesEscaleras.ServidorJuegoSE.Casilla[] casillasRecibidas, SerpientesEscaleras.ServidorJuegoSE.Portal[] portalesRecibidos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/CambiarPortales")]
        System.Threading.Tasks.Task CambiarPortalesAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Casilla[] casillasRecibidas, SerpientesEscaleras.ServidorJuegoSE.Portal[] portalesRecibidos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorMultijugadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirMensajeLobby")]
        void RecibirMensajeLobby(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirMensajeMiembroLobby")]
        void RecibirMensajeMiembroLobby(bool entrada, string apodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/EntrarJuego")]
        void EntrarJuego(SerpientesEscaleras.ServidorJuegoSE.Casilla[] casillas, SerpientesEscaleras.ServidorJuegoSE.Portal[] portales);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/SolicitarCrearTablero")]
        void SolicitarCrearTablero();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirMensaje")]
        void RecibirMensaje(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/RecibirMensajeMiembro")]
        void RecibirMensajeMiembro(bool entrada, string apodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/ElegirFicha")]
        void ElegirFicha(string apodo, SerpientesEscaleras.ServidorJuegoSE.Ficha[] fichasEscogidas);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/MostrarFichaElegida")]
        void MostrarFichaElegida(SerpientesEscaleras.ServidorJuegoSE.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/Tirar")]
        void Tirar(string apodo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/MostrarTiro")]
        void MostrarTiro(SerpientesEscaleras.ServidorJuegoSE.Ficha ficha);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/MostrarNuevosPortales")]
        void MostrarNuevosPortales(SerpientesEscaleras.ServidorJuegoSE.Portal[] portales);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdministradorMultijugador/MostrarGanador")]
        void MostrarGanador(SerpientesEscaleras.ServidorJuegoSE.Ficha ficha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministradorMultijugadorChannel : SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministradorMultijugadorClient : System.ServiceModel.DuplexClientBase<SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugador>, SerpientesEscaleras.ServidorJuegoSE.IAdministradorMultijugador {
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdministradorMultijugadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int CrearSala(SerpientesEscaleras.ServidorJuegoSE.Sala sala) {
            return base.Channel.CrearSala(sala);
        }
        
        public System.Threading.Tasks.Task<int> CrearSalaAsync(SerpientesEscaleras.ServidorJuegoSE.Sala sala) {
            return base.Channel.CrearSalaAsync(sala);
        }
        
        public SerpientesEscaleras.ServidorJuegoSE.Sala[] ConsultarSalasDisponibles() {
            return base.Channel.ConsultarSalasDisponibles();
        }
        
        public System.Threading.Tasks.Task<SerpientesEscaleras.ServidorJuegoSE.Sala[]> ConsultarSalasDisponiblesAsync() {
            return base.Channel.ConsultarSalasDisponiblesAsync();
        }
        
        public string[] ConsultarJugadoresSala(int idSala) {
            return base.Channel.ConsultarJugadoresSala(idSala);
        }
        
        public System.Threading.Tasks.Task<string[]> ConsultarJugadoresSalaAsync(int idSala) {
            return base.Channel.ConsultarJugadoresSalaAsync(idSala);
        }
        
        public void UnirseSala(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            base.Channel.UnirseSala(idSala, jugador);
        }
        
        public System.Threading.Tasks.Task UnirseSalaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.UnirseSalaAsync(idSala, jugador);
        }
        
        public bool ValidarSala(int idSala) {
            return base.Channel.ValidarSala(idSala);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarSalaAsync(int idSala) {
            return base.Channel.ValidarSalaAsync(idSala);
        }
        
        public void EnviarMensaje(int idSala, string mensaje) {
            base.Channel.EnviarMensaje(idSala, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(int idSala, string mensaje) {
            return base.Channel.EnviarMensajeAsync(idSala, mensaje);
        }
        
        public void SalirChat(int idSala) {
            base.Channel.SalirChat(idSala);
        }
        
        public System.Threading.Tasks.Task SalirChatAsync(int idSala) {
            return base.Channel.SalirChatAsync(idSala);
        }
        
        public void IniciarJuego(int idSala) {
            base.Channel.IniciarJuego(idSala);
        }
        
        public System.Threading.Tasks.Task IniciarJuegoAsync(int idSala) {
            return base.Channel.IniciarJuegoAsync(idSala);
        }
        
        public void UnirseJuego(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            base.Channel.UnirseJuego(idSala, jugador);
        }
        
        public System.Threading.Tasks.Task UnirseJuegoAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Jugador jugador) {
            return base.Channel.UnirseJuegoAsync(idSala, jugador);
        }
        
        public void EnviarMensajeJuego(int idSala, string mensaje) {
            base.Channel.EnviarMensajeJuego(idSala, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeJuegoAsync(int idSala, string mensaje) {
            return base.Channel.EnviarMensajeJuegoAsync(idSala, mensaje);
        }
        
        public void SalirJuego(int idSala) {
            base.Channel.SalirJuego(idSala);
        }
        
        public System.Threading.Tasks.Task SalirJuegoAsync(int idSala) {
            return base.Channel.SalirJuegoAsync(idSala);
        }
        
        public void AsignarFicha(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha) {
            base.Channel.AsignarFicha(idSala, ficha);
        }
        
        public System.Threading.Tasks.Task AsignarFichaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha) {
            return base.Channel.AsignarFichaAsync(idSala, ficha);
        }
        
        public void RecibirTiro(int idSala, int numDado) {
            base.Channel.RecibirTiro(idSala, numDado);
        }
        
        public System.Threading.Tasks.Task RecibirTiroAsync(int idSala, int numDado) {
            return base.Channel.RecibirTiroAsync(idSala, numDado);
        }
        
        public void CambiarPosicionFicha(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha) {
            base.Channel.CambiarPosicionFicha(idSala, ficha);
        }
        
        public System.Threading.Tasks.Task CambiarPosicionFichaAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Ficha ficha) {
            return base.Channel.CambiarPosicionFichaAsync(idSala, ficha);
        }
        
        public void CambiarPortales(int idSala, SerpientesEscaleras.ServidorJuegoSE.Casilla[] casillasRecibidas, SerpientesEscaleras.ServidorJuegoSE.Portal[] portalesRecibidos) {
            base.Channel.CambiarPortales(idSala, casillasRecibidas, portalesRecibidos);
        }
        
        public System.Threading.Tasks.Task CambiarPortalesAsync(int idSala, SerpientesEscaleras.ServidorJuegoSE.Casilla[] casillasRecibidas, SerpientesEscaleras.ServidorJuegoSE.Portal[] portalesRecibidos) {
            return base.Channel.CambiarPortalesAsync(idSala, casillasRecibidas, portalesRecibidos);
        }
    }
}
