//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int Id { get; set; }
        public string correo { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public bool validada { get; set; }
        public bool secionIniciada { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
